modLoader="javafml"
loaderVersion="[4.0,)"
license="MIT"

[[mods]]
modId="splitscreen"
version="${mod_version}"
displayName="Splitscreen Support"
description="Window positioning assistance for splitscreen play."
authors=["pcal"]
logoFile="icon.png"

[[dependencies.splitscreen]]
modId="neoforge"
mandatory=true
versionRange="[${neoforge_version},)"

[[mixins]]
config = "splitscreen.mixins.json"
